name: IridiumSkyblock
main: com.iridium.iridiumskyblock.IridiumSkyblock
version: ${version}
authors: [Peaches_MLG, SoKnight]
depend: [Vault]
softdepend: [PlaceholderAPI, Essentials, EssentialsSpawn, RoseStacker, WildStacker, UltimateStacker, WorldEdit]
loadbefore: [Multiverse-Core]
description: Skyblock Redefined
api-version: 1.13

commands:
  iridiumskyblock:
    aliases: [island, is]
    description: Main plugin command